### ISSUE TITLE
有bug?

### ISSUE THREAD

**Issue by dsmnoi** [dovela/CloudFlare_DNS_Record#1]
如果有20多个A记录   脚本只能获取高排序的record_id  而排序在最下面一直不能获取record_id

**Comment by dovela** [comment]
看了下，明晚就能弄好，APi默认请求result就是20条，调大了就行了

**Comment by dsmnoi** [comment]
谢谢

**Comment by dovela** [comment]
已修复，现在不会再有A记录数限制了
