### ISSUE TITLE
测试的时候，tcp检测好像并没有获取正确结果

### ISSUE THREAD

**Issue by meethu** [dovela/CloudFlare_DNS_Record#3]
awk -F '[:}]' '{print $21}'

这一块命令并未执行，无论是ip被墙还是正常，均是' '和false作对比

**Comment by dovela** [comment]
我知道了，今天我检查一下

**Comment by dovela** [comment]
已修复

**Comment by meethu** [comment]
好的，其实ipcheck有时候的准确率并不高（并不知道为什么）

还有个站点https://torch.njs.app/ 也可以参考

除此之外 curl 应该加入超时判断，超时后直接退出脚本或直接tcp 定义 false 以防在个别某些情况下，卡在这部分

**Comment by jameqq** [comment]
IP更换有点频繁，可能就因为楼上说的测试不准确 怎么延迟测试加长更换IP的时间

**Comment by dovela** [comment]
@meethu 是卡在哪个curl？tcp阻断检测成功率是有些麻烦，用ipcheck是妥协。torch那个有api吗？

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI 8 SE 发送_

**Comment by dovela** [comment]
准确率不高是因为吊机的国内检测服务器就一个吧

**Comment by jameqq** [comment]
现在几个小时就自动更换了，墙的频率基本上2天一次，怎么设置夜里更换 这样影响小点

**Comment by dovela** [comment]
@TBQin 只是这样的话，你改下crontab就好了，只让脚本在特定小时段内运行

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI 8 SE 发送_

**Comment by dsmnoi** [comment]
@dovela 自动换ip频率的确很高 别用吊机的了 建议参考逗比的或者使用https://torch.njs.app

**Comment by dovela** [comment]
> @dovela 自动换ip频率的确很高 别用吊机的了 建议参考逗比的或者使用https://torch.njs.app

参考逗比的是指哪个项目？torch的我看了，我不懂php。。但他那似乎并没有api接口，要调用的话需要把他那整个项目合进来。做了个小更新，应该会缓解换ip的频率。很遗憾，受限于我个人水平和tcp检测手段的不成熟，很难更进一步了。
torch那个网站如果有有效的调用方法，请告诉我，我没想到什么好办法。

**Comment by dsmnoi** [comment]
@dovela https://github.com/ToyoDAdoubiBackup/doubi/blob/master/gfw_push.sh

这个项目 你看看有没有可能用这个方法
